import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders })
  }

  try {
    const authHeader = req.headers.get('Authorization')
    if (!authHeader) {
      return new Response(
        JSON.stringify({ error: 'Unauthorized' }),
        { status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    const supabaseAdmin = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    )

    // Verify the calling user is admin/owner/manager/staff
    const supabaseClient = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_ANON_KEY') ?? '',
      { global: { headers: { Authorization: authHeader } } }
    )

    const { data: { user: callingUser }, error: authError } = await supabaseClient.auth.getUser()
    if (authError || !callingUser) {
      return new Response(
        JSON.stringify({ error: 'Unauthorized' }),
        { status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    // Check if calling user has permission to create members
    const { data: callerRoles } = await supabaseAdmin
      .from('user_roles')
      .select('role')
      .eq('user_id', callingUser.id)
      .in('role', ['owner', 'admin', 'manager', 'staff'])

    if (!callerRoles || callerRoles.length === 0) {
      return new Response(
        JSON.stringify({ error: 'Insufficient permissions' }),
        { status: 403, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    const { 
      email, 
      fullName, 
      phone, 
      branchId,
      gender,
      dateOfBirth,
      address,
      emergencyContactName,
      emergencyContactPhone,
      source,
      fitnessGoals,
      healthConditions,
      referredBy,
      createdBy
    } = await req.json()

    if (!email || !fullName || !branchId) {
      return new Response(
        JSON.stringify({ error: 'Email, fullName, and branchId are required' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    // Check if user with this email already exists
    const { data: existingUsers } = await supabaseAdmin.auth.admin.listUsers()
    const existingUser = existingUsers?.users?.find(u => u.email?.toLowerCase() === email.toLowerCase())
    
    if (existingUser) {
      return new Response(
        JSON.stringify({ error: 'A user with this email already exists', code: 'email_exists' }),
        { status: 422, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    // Generate a temporary password
    const tempPassword = crypto.randomUUID().slice(0, 12)

    // Create the user with email confirmed
    const { data: authData, error: createError } = await supabaseAdmin.auth.admin.createUser({
      email,
      password: tempPassword,
      email_confirm: true,
      user_metadata: { full_name: fullName }
    })

    if (createError) {
      console.error('Auth create error:', createError)
      throw createError
    }

    console.log('User created:', authData.user.id)

    // Update profile with all details
    const { error: profileError } = await supabaseAdmin
      .from('profiles')
      .update({ 
        full_name: fullName, 
        phone: phone || null,
        gender: gender || null,
        date_of_birth: dateOfBirth || null,
        address: address || null,
        emergency_contact_name: emergencyContactName || null,
        emergency_contact_phone: emergencyContactPhone || null,
        must_set_password: true 
      })
      .eq('id', authData.user.id)

    if (profileError) {
      console.error('Profile update error:', profileError)
    }

    // Assign member role
    const { error: roleError } = await supabaseAdmin
      .from('user_roles')
      .insert({ user_id: authData.user.id, role: 'member' })

    if (roleError) {
      console.error('Role insert error:', roleError)
      throw roleError
    }

    // Create member record with all fields including created_by
    const { data: member, error: memberError } = await supabaseAdmin
      .from('members')
      .insert({
        user_id: authData.user.id,
        branch_id: branchId,
        member_code: '', // Will be generated by trigger
        status: 'active',
        source: source || 'walk-in',
        fitness_goals: fitnessGoals || null,
        health_conditions: healthConditions || null,
        referred_by: referredBy || null,
        created_by: createdBy || callingUser.id, // Track who created this member
      })
      .select('id, member_code')
      .single()

    if (memberError) {
      console.error('Member insert error:', memberError)
      throw memberError
    }

    console.log('Member created:', member.id)

    return new Response(
      JSON.stringify({ 
        success: true, 
        userId: authData.user.id,
        memberId: member.id,
        memberCode: member.member_code,
        message: 'Member created successfully. They will set their password on first login.'
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    )
  } catch (error: unknown) {
    console.error('Error in create-member-user:', error)
    const message = error instanceof Error ? error.message : 'Unknown error'
    return new Response(
      JSON.stringify({ error: message }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    )
  }
})
