
-- 1. Add trainer_id, commission_percentage, base_salary to contracts
ALTER TABLE public.contracts 
  ADD COLUMN IF NOT EXISTS trainer_id uuid REFERENCES public.trainers(id),
  ADD COLUMN IF NOT EXISTS commission_percentage numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS base_salary numeric DEFAULT 0;

-- Allow contract to target either employee or trainer (but at least one)
-- Drop existing constraint if any, then add
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints 
    WHERE constraint_name = 'chk_contract_target' AND table_name = 'contracts'
  ) THEN
    ALTER TABLE public.contracts ADD CONSTRAINT chk_contract_target
      CHECK (employee_id IS NOT NULL OR trainer_id IS NOT NULL);
  END IF;
END $$;

-- 2. Add website_theme JSONB column to organization_settings for CMS
ALTER TABLE public.organization_settings 
  ADD COLUMN IF NOT EXISTS website_theme jsonb DEFAULT '{}'::jsonb;

-- 3. Create renewal invoice generation function
CREATE OR REPLACE FUNCTION public.generate_renewal_invoices()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = 'public'
AS $function$
DECLARE
  ms RECORD;
  inv_exists boolean;
  new_invoice_id uuid;
BEGIN
  FOR ms IN
    SELECT m.id as membership_id, m.member_id, m.branch_id, m.plan_id, 
           mp.name as plan_name, mp.price as plan_price,
           mem.user_id
    FROM memberships m
    JOIN membership_plans mp ON m.plan_id = mp.id
    JOIN members mem ON mem.id = m.member_id
    WHERE m.status = 'active'
    AND m.end_date = CURRENT_DATE + INTERVAL '7 days'
  LOOP
    -- Check if renewal invoice already exists
    SELECT EXISTS(
      SELECT 1 FROM invoices i 
      JOIN invoice_items ii ON ii.invoice_id = i.id
      WHERE i.member_id = ms.member_id 
      AND ii.reference_type = 'membership_renewal'
      AND i.status = 'pending'
      AND i.created_at > CURRENT_DATE - INTERVAL '10 days'
    ) INTO inv_exists;
    
    IF NOT inv_exists THEN
      -- Create renewal invoice (invoice_number generated by trigger)
      INSERT INTO invoices (branch_id, member_id, total_amount, status, due_date)
      VALUES (ms.branch_id, ms.member_id, ms.plan_price, 'pending', CURRENT_DATE + INTERVAL '7 days')
      RETURNING id INTO new_invoice_id;

      -- Add invoice item
      INSERT INTO invoice_items (invoice_id, description, unit_price, quantity, total_amount, reference_type, reference_id)
      VALUES (new_invoice_id, 'Membership Renewal - ' || ms.plan_name, ms.plan_price, 1, ms.plan_price, 'membership_renewal', ms.membership_id::text);
      
      -- Notify member
      INSERT INTO notifications (user_id, branch_id, title, message, type, category)
      VALUES (ms.user_id, ms.branch_id, 'Renewal Invoice Generated',
        'Your membership renewal invoice for ' || ms.plan_name || ' (₹' || ms.plan_price || ') has been generated. Due in 7 days.',
        'info', 'billing');
    END IF;
  END LOOP;
END;
$function$;

-- 4. Schedule renewal invoice generation daily at 2 AM UTC
SELECT cron.schedule(
  'generate-renewal-invoices',
  '0 2 * * *',
  $$SELECT public.generate_renewal_invoices()$$
);
